name: CI - Build y Tests MaxFit

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Todas las instrucciones "run" se hacen dentro de la carpeta proyectoFinal1
    defaults:
      run:
        working-directory: proyectoFinal1

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Dar permisos de ejecución al wrapper de Maven
        run: chmod +x mvnw

      - name: Instalar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar proyecto (sin tests para evitar errores)
        run: ./mvnw -q clean package -DskipTests
